# Generated by Django 4.1 on 2023-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(max_length=16),
        ),
    ]
