# Generated by Django 4.1 on 2023-10-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0005_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
